global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'spring-boot-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - host.docker.internal:8081  # user-service
          - host.docker.internal:8082  # product-service
          - host.docker.internal:8083  # order-service
          - host.docker.internal:8084  # payment-service
          - host.docker.internal:8085  # notification-service
          - host.docker.internal:8086  # audit-service
          - host.docker.internal:8080  # api-gateway
